# Site settings
title: Applied Data Science
email: tian.zheng@columbia.edu
description: > # this means to ignore newlines until "baseurl:"
  This GitHub organization is for Stat W4249 Applied Data Science, a project-based hands-on course in data science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://TZStatsADS.github.io" # the base hostname & protocol for your site
twitter_username: tz33cu
github_username:  tz33cu

# Build settings
markdown: kramdown
highlighter: rouge