title: Applied Data Science @ Columbia
description: "Class Blog"

url: http://TZstatsADS.github.io/
port: 3000
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Tian Zheng
  github: tz33cu
  twitter: tz33cu